### ISSUE TITLE
Would you be willing to make func charEncode(src []rune) []rune {} public?

### ISSUE THREAD

**Issue by angelahuqing** [caltechlibrary/pairtree#1]
I work for the UCLA Library, and we are trying to develop a suite of tools that work with the pairtree structure. We have a case that would utilize `charEncode()` for attaching file names to the end of our pairtree-paths. Would you be willing to make this function a public one?

**Comment by rsdoiel** [comment]
That should be doable. Could you end an example code fragment of you'd like it to work? That way I can make sure I implement it in a useful way for you and also doesn't break my own project code.

**Comment by angelahuqing** [comment]
```
// CreatePP creates the full pairpath given the root, id, and prefix
func CreatePP(id, ptRoot, prefix string) (string, error) {
	if strings.TrimSpace(ptRoot) == "" {
		return "", error_msgs.Err3
	}

	if strings.TrimSpace(id) == "" {
		return "", error_msgs.Err4
	}

	if strings.HasPrefix(id, prefix) {
		// Remove the prefix from id
		id = strings.TrimPrefix(id, prefix)
	} else {
		return "", fmt.Errorf("%w, id: '%s', prefix: '%s'", error_msgs.Err5, id, prefix)
	}

	ptRoot = filepath.Join(ptRoot, rootDir)

	pairPath := caltech_pairtree.Encode(id)

	id = EncodeChar(id)
	pairPath = filepath.Join(pairPath, id)
	pairPath = filepath.Join(ptRoot, pairPath)
	return pairPath, nil
}

```

At the moment we have our own function that delivers the same output as `charEncode(src[]rune) ` called `EncodeChar(id)` which also takes a string and returns a string with the special characters encoded. I believe the use case would be the same as what `charEncode(src[]rune)` already does.

**Comment by rsdoiel** [comment]
Thanks for the suggestion, I've release v1.0.4 with charEncode and charDecode renamed CharEncode and CharDecode.  All the best, Robert.
